FROM microsoft/dotnet:2.2-aspnetcore-runtime
WORKDIR C:/Software

RUN curl -O -L https://github.com/sbalanchickoo/Plutus/releases/download/Plutus.Bankmetadata.1.0.7/Plutus.Bankmetadata.zip
RUN tar.exe -xf Plutus.Bankmetadata.zip

EXPOSE 5001
ENTRYPOINT [ "dotnet", "Plutus.Bankmetadata.Service.API.dll"]
