FROM microsoft/dotnet:2.2-aspnetcore-runtime
WORKDIR C:/Software

RUN curl -O -L https://github.com/sbalanchickoo/Plutus/releases/download/Plutus.Expenses.1.0.1/Plutus.Expenses.zip
RUN tar.exe -xf Plutus.Expenses.zip

EXPOSE 5003
ENTRYPOINT [ "dotnet", "Plutus.Expenses.Service.API.dll"]

#docker build -t expenses .
#docker run -d -p 5003:5003 --name expenses -v C:\Docker\Expenses:C:\Software\Inputdata expenses -m 1024m --cpuset-cpus="1"